// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SubInvestorSetup.Models;

namespace SubInvestorSetup.Migrations
{
    [DbContext(typeof(InvestorContext))]
    partial class InvestorContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SubInvestorSetup.Models.InvestorLink", b =>
                {
                    b.Property<int>("InvestorSetupId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("ApprovedDate");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("CreatedDate");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DeletedDate");

                    b.Property<string>("DeletedReason")
                        .HasColumnType("varchar(256)");

                    b.Property<string>("DeployedBy")
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("DeployedDate");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("varchar(256)");

                    b.Property<int>("InvestorNo");

                    b.Property<int>("InvestorSubFrom");

                    b.Property<int>("InvestorSubTo");

                    b.Property<int>("ModelAfterInvestorNo");

                    b.Property<int>("ModelAfterInvestorSub");

                    b.Property<int?>("Status");

                    b.HasKey("InvestorSetupId");

                    b.ToTable("InvestorLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
